runtime: python39  # or python311 if available
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  SECRET_KEY: 'your_secret_key_here'

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto
