"""Add Channel model and remove channel from WalkieTalkie

Revision ID: 2f93ba6ce6d5
Revises: 
Create Date: 2024-10-19 14:45:20.025653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f93ba6ce6d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('walkie_talkies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_lent', sa.Boolean(), nullable=True),
    sa.Column('current_holder', sa.String(length=100), nullable=True),
    sa.Column('is_charged', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_number', sa.Integer(), nullable=False),
    sa.Column('walkie_talkie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['walkie_talkie_id'], ['walkie_talkies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('walkie_talkie_id', 'channel_number', name='_walkie_channel_uc')
    )
    op.create_table('rentals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('walkie_talkie_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('lend_time', sa.DateTime(), nullable=False),
    sa.Column('return_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['walkie_talkie_id'], ['walkie_talkies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rentals')
    op.drop_table('channels')
    op.drop_table('walkie_talkies')
    op.drop_table('departments')
    # ### end Alembic commands ###
